# -*- coding: utf-8 -*-
"""GENERATIVE-AI project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nvfEiUvUwlBKzPsiJhSON1B9bWZSYSsC
"""

!pip install scikit-learn nltk seaborn

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.exceptions import UndefinedMetricWarning

import nltk
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

nltk.download("stopwords")
warnings.filterwarnings("ignore", category=UndefinedMetricWarning)

data = pd.read_csv("news_articless.csv")  # <-- your file name

print("Shape:", data.shape)
print("\nColumns:", data.columns.tolist())
print("\nFirst few rows:\n")
display(data.head())

print("\nCategory counts:\n")
print(data["category"].value_counts())

def preprocess(text):
    text = str(text).lower()
    return text

data["clean_text"] = data["article"].apply(preprocess)

data[["article", "clean_text", "category"]].head()

X = data["clean_text"]
y = data["category"]

tfidf = TfidfVectorizer(max_features=5000)
X_tfidf = tfidf.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,
    y,
    test_size=0.2,       # 80% train, 20% test
    random_state=42,
    stratify=y
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

model = MultinomialNB()
model.fit(X_train, y_train)

print("Model trained ")

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred, zero_division=0))

labels = ["politics", "sports", "entertainment", "technology", "business"]

cm = confusion_matrix(y_test, y_pred, labels=labels)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix – ClassiNews")
plt.tight_layout()
plt.show()

def predict_category(text):
    clean = preprocess(text)
    vec = tfidf.transform([clean])
    pred = model.predict(vec)[0]
    probs = model.predict_proba(vec)[0]
    class_probs = dict(zip(model.classes_, probs))
    return pred, class_probs

import joblib

joblib.dump(tfidf, "tfidf_vectorizer.pkl")
joblib.dump(model, "news_classifier_nb.pkl")

print("Saved: tfidf_vectorizer.pkl and news_classifier_nb.pkl ")

